{% set name = "srsly" %}
{% set version = "2.5.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7589a35dd6bf1d177803c4ed454098f2f690b3704b80cca337a50be95ba59b3a
  patches:
    - patches/0001-unvendor-cloudpickle.patch
    - patches/0002-unvendor-ujson.patch
    # The "vendored" msgpack is actually custom code that extends msgpack, not just a copy of upstream msgpack-python. Won`t unvendor.
    - patches/0003-fix-test_json_api.py-indents.patch
    - patches/0004-fix-add-support-legasy-ruamel_yaml-import.patch

build:
  number: 0
  skip: true  # [py<39 or py>315]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.29.1
  run:
    - python
    - catalogue >=2.0.3,<2.1.0
    # https://github.com/explosion/srsly/blob/release-v2.5.4/srsly/cloudpickle/__init__.py#L6
    - cloudpickle >=3.1.2,<4
    # https://github.com/explosion/srsly/blob/release-v2.5.4/srsly/ujson/version.h#L39
    - ujson >=1.35
    # https://github.com/explosion/srsly/blob/release-v2.5.4/srsly/ruamel_yaml/__init__.py#L6
    - ruamel.yaml >=0.16.7

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pip
    - pytest
    - pytest-timeout >=1.3.3
    - mock
    - numpy >=1.15.0
    - psutil
  commands:
    - pip check
    - python -m pytest -vv --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/srsly
  summary: Modern high-performance serialization utilities for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python
  description: |
    This package bundles some of the best Python serialization libraries into one standalone package, 
    with a high-level API that makes it easy to write code that's correct across platforms and Pythons. 
    This allows us to provide all the serialization utilities we need in a single binary wheel. 
    Currently supports JSON, JSONL, MessagePack, Pickle and YAML.
  doc_url: https://github.com/explosion/srsly/blob/master/README.md
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
