{% set name = "srsly" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4092bc843c71b7595c6c90a0302a197858c5b9fe43067f62ae6a45bc3baa1c19
  patches:
    - patches/0001-unvendor-cloudpickle.patch
    - patches/0002-unvendor-ujson.patch
    - patches/0003-unvendor-ruamel_yaml.patch
    # The "vendored" msgpack is actually custom code that extends msgpack, not just a copy of upstream msgpack-python. Won`t unvendor.

build:
  number: 0
  script: 
  - rd /q /s "%SRC_DIR%\srsly\cloudpickle"  # [win]
  - rd /q /s "%SRC_DIR%\srsly\ujson"  # [win]
  - rd /q /s "%SRC_DIR%\srsly\ruamel_yaml"  # [win]
  - rm -rf "${SRC_DIR}/srsly/cloudpickle"  # [unix]
  - rm -rf "${SRC_DIR}/srsly/ujson"  # [unix]
  - rm -rf "${SRC_DIR}/srsly/ruamel_yaml"  # [unix]
  - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39 or py>315]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.29.1
  run:
    - python
    - catalogue >=2.0.3,<2.1.0
    # https://github.com/explosion/srsly/blob/release-v2.5.2/srsly/cloudpickle/__init__.py#L8
    - cloudpickle >=2.2.0
    # https://github.com/explosion/srsly/blob/release-v2.5.2/srsly/ujson/version.h#L39
    - ujson >=1.35
    # https://github.com/explosion/srsly/blob/release-v2.5.2/srsly/ruamel_yaml/__init__.py#L6
    - ruamel_yaml >=0.16.7

# Won`t run tests for these modules, they are tested in their meta.yaml recipes:
{% set deselect_tests = " --deselect=tests/cloudpickle" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/ujson" %}
{% set deselect_tests = deselect_tests + " --deselect=tests/ruamel_yaml" %}
test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pip
    - pytest
    - pytest-timeout >=1.3.3
    - mock
    - numpy >=1.15.0
    - psutil
  commands:
    - pip check
    - python -m pytest -vv --tb=native --pyargs {{ name }} {{ deselect_tests }}

about:
  home: https://github.com/explosion/srsly
  summary: Modern high-performance serialization utilities for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python
  description: |
    This package bundles some of the best Python serialization libraries into one standalone package, 
    with a high-level API that makes it easy to write code that's correct across platforms and Pythons. 
    This allows us to provide all the serialization utilities we need in a single binary wheel. 
    Currently supports JSON, JSONL, MessagePack, Pickle and YAML.
  doc_url: https://github.com/explosion/srsly/blob/master/README.md
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
