{% set name = "srsly" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab1b4bf6cf3e29da23dae0493dd1517fb787075206512351421b89b4fc27c77e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - srsly.read_json.v1 = srsly:read_json
    - srsly.read_jsonl.v1 = srsly:read_jsonl
    - srsly.read_yaml.v1 = srsly:read_yaml
    - srsly.read_msgpack.v1 = srsly:read_msgpack
  skip: True  # [py<39 or py>313]
  ignore_run_exports:
    - libcxx

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.29.1
  run:
    - python
    - catalogue >=2.0.3,<2.1.0

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pip
    - pytest
    - pytest-timeout >=1.3.3
    - mock
    - numpy >=1.15.0
    - psutil
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/srsly
  summary: Modern high-performance serialization utilities for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python
  description: |
    This package bundles some of the best Python serialization libraries into one standalone package, 
    with a high-level API that makes it easy to write code that's correct across platforms and Pythons. 
    This allows us to provide all the serialization utilities we need in a single binary wheel. 
    Currently supports JSON, JSONL, MessagePack, Pickle and YAML.
  doc_url: https://github.com/explosion/srsly/blob/master/README.md
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
