{% set name = "srsly" %}
{% set version = "2.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/srsly-{{ version }}.tar.gz
  sha256: b24d95a65009c2447e0b49cda043ac53fecf4f09e358d87a57446458f91b8a91

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<36]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.29.1,<0.30.0
  run:
    - python
    - catalogue >=2.0.3,<2.1.0

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pip
    - pytest
    - pytest-timeout >=1.3.3
    - mock
    - numpy >=1.15.0
    - psutil
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/srsly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python
  description: |
    Modern high-performance serialization utilities for Python (JSON, MessagePack, Pickle)
  doc_url: https://github.com/explosion/srsly/blob/master/README.md
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
