{% set name = "srsly" %}
{% set version = "2.4.5" %}
{% set sha256sum = "c842258967baa527cea9367986e42b8143a1a890e7d4a18d25a36edc3c7a33c7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<36]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.25
  run:
    - python
    - catalogue >=2.0.3,<2.1.0

test:
  imports:
    - srsly
    - srsly.tests
  requires:
    - pip
    - pytest 
    - pytz
    - mock 
    - numpy >=1.15.0
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ name }}

about:
  home: https://github.com/explosion/srsly
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Modern high-performance serialization utilities for Python

  doc_url: https://github.com/explosion/srsly/blob/master/README.md
  dev_url: https://github.com/explosion/srsly

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
